-- 版本列表sql
CREATE TABLE IF NOT EXISTS "T_JDK_VERSION" (
  "ID" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
  "UK_VERSION" TEXT(32) NOT NULL, -- 版本唯一标识
  "VM_VENDOR" TEXT(16) NOT NULL,  -- 厂商
  "MAIN_VERSION" TEXT(16) NOT NULL,-- 主版本
  "JAVA_VERSION" TEXT(32) NOT NULL, -- 完整版本
  "RELEASE_DATE" TEXT(32) NOT NULL, -- 发布时间
  "FILE_NAME" TEXT NOT NULL, -- 文件名
  "FILE_SIZE" TEXT(16) NOT NULL, -- 文件大小
  "FILE_TYPE" TEXT(16) NOT NULL, -- 文件类型
  "CAN_DOWNLOAD" integer NOT NULL, -- 是否可以下载
  "DOWNLOAD_URL" TEXT NOT NULL -- 下载地址
);

-- 用户版本列表
CREATE TABLE IF NOT EXISTS "T_USER_JDK_VERSION" (
  "ID" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
  "UK_VERSION" TEXT(32) NOT NULL, -- 版本唯一标识
  "VM_VENDOR" TEXT(16) NOT NULL, -- 厂商
  "MAIN_VERSION" TEXT(16) NOT NULL, -- 主版本
  "JAVA_VERSION" TEXT(32) NOT NULL, -- 完整版本
  "LOCAL_HOME_PATH" TEXT, -- 本地存放路径
  "STATUS" TEXT(16) NOT NULL, -- 状态
  "SOURCE" TEXT(8) NOT NULL, -- 来源
  "CREATED_AT" TEXT(32) -- 创建时间
);

-- 用户版本下载记录表
CREATE TABLE IF NOT EXISTS "T_INSTALL_RECORD" (
    "ID" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
    "UK_VERSION" TEXT(32) NOT NULL, -- 版本唯一标识
    "VM_VENDOR" TEXT(16) NOT NULL, -- 厂商
    "MAIN_VERSION" TEXT(16) NOT NULL, -- 主版本
    "JAVA_VERSION" TEXT(32) NOT NULL, -- 完整版本
    "FILE_NAME" TEXT NOT NULL, -- 文件名
    "FILE_SIZE" TEXT(16) NOT NULL, -- 文件大小
    "FILE_TYPE" TEXT(16) NOT NULL, -- 文件类型
    "DOWNLOAD_URL" TEXT NOT NULL, -- 下载地址
    "DOWNLOAD_STATUS" TEXT(16) NOT NULL, -- 下载状态
    "DOWNLOAD_FILE_FOLDER" TEXT NOT NULL, -- 下载文件存放文件夹
    "JDK_PACKAGE_URL" TEXT NOT NULL, -- jdk安装包地址
    "INSTALLED_FOLDER" TEXT NOT NULL, -- jdk安装文件夹
    "INSTALLED_JAVA_HOME" TEXT, -- jdk安装成功后的home路径
    "DOWNLOAD_PROGRESS" REAL NOT NULL, -- 下载的进度
    "DOWNLOAD_END_AT" TEXT(32), -- 下载的进度
    "CREATED_AT" TEXT(32) -- 创建时间
    );

-- 用户配置
CREATE TABLE IF NOT EXISTS "T_USER_CONFIG_INFO" (
  "ID" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
  "DIC_KEY" TEXT(16) NOT NULL, -- 配置key
  "DIC_VALUE" TEXT -- 配置值
  "CREATED_AT" TEXT(32), -- 创建时间
  CONSTRAINT "UK_KEY" UNIQUE ("DIC_KEY")
);